=== MiguelG7/entregas_sis_webII/ej 1 json _schema/pelicula/validar_pelicula.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
      "title": { "type": "string" },
      "year": { "type": "integer", "minimum": 1900 },
      "genre": {
        "type": "array",
        "items": { "type": "string" }
      },
      "director": { "type": "string" },
      "rating": { "type": "number", "minimum": 0, "maximum": 10 },
      "actors": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": { "type": "string" },
            "role": { "type": "string" }
          },
          "required": ["name", "role"]
        }
      }
    },
    "required": ["title", "year", "genre", "director", "rating", "actors"]
  }

=== MiguelG7/entregas_sis_webII/ej 1 json _schema/pelicula/pelicula.json
{
    "title": "Inception",
    "year": 2010,
    "genre": ["Action", "Sci-Fi"],
    "director": "Christopher Nolan",
    "rating": 8.8,
    "actors": [
      {
        "name": "Leonardo DiCaprio",
        "role": "Cobb"
      },
      {
        "name": "Joseph Gordon-Levitt",
        "role": "Arthur"
      }
    ]
  }
